name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greetings
        run: 
          echo "Hello World!" 
          echo "This is my first workflow"
      - name: Print Exit Statement
        run: echo "Done - Bye! End of Workflow!!"
        
    
